//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProject()
        {
            this.WorkField = new HashSet<WorkField>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Project { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkField> WorkField { get; set; }
    }
}
