//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkField
    {
        public int ID { get; set; }
        public Nullable<int> ID_UP { get; set; }
        public Nullable<int> Element_ID { get; set; }
        public Nullable<int> PositionX { get; set; }
        public Nullable<int> PositionY { get; set; }
        public Nullable<int> Rotate { get; set; }
    
        public virtual Elements Elements { get; set; }
        public virtual UserProject UserProject { get; set; }
    }
}
