//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkField
    {
        public int ID { get; set; }
        public Nullable<int> ID_Project { get; set; }
        public Nullable<int> Element_ID { get; set; }
        public Nullable<int> PisitionX { get; set; }
        public Nullable<int> PositionY { get; set; }
        public Nullable<int> PositionZ { get; set; }
    
        public virtual Elements Elements { get; set; }
        public virtual Project Project { get; set; }
    }
}
